### ISSUE TITLE
Vector Docs reference wrong GIthub Repository

### ISSUE THREAD

**Issue by TtheBC01** [connext/vector-router-docker-compose#2]
https://docs.connext.network/running-a-router-easy-mode#k7-setup-router

In the docs for 'Running a Router - Easy Mode', the user is instructed to pull from vector-node-docker-compose, but it seems the repository is actually named vector-router-docker-compose.

**Comment by rhlsthrm** [comment]
Correct! And fixed. Thank you for the nice catch!
