### ISSUE TITLE
manifest unknown

### ISSUE THREAD

**Issue by jacobabiola** [connext/vector-router-docker-compose#4]
Hello,

when i try docker-compose create i get this error message.

`Pulling db-node (connextproject/vector_database:0.2.5)...
ERROR: manifest for connextproject/vector_database:0.2.5 not found: manifest unknown: manifest unknown`

what could be wrong?

**Comment by rhlsthrm** [comment]
Hello, can you please use this tag: 0.2.5-beta.18?

Thanks!

**Comment by jacobabiola** [comment]
Thanks, mate, I have been googling how to add a tag since you mentioned but didn't quite understand how that works for my particular error.

could you point me to how to do this? :)

**Comment by jacobabiola** [comment]
Thanks, i figured it out.. you were referring to the version number on .env file.  :) 

Thanks a lot
